[package]
name = "voicevox_core_wasm_api"
version.workspace = true
edition.workspace = true
publish.workspace = true
build = "build.rs"

[lib]
crate-type = ["cdylib"]
name = "voicevox_core"

[dependencies]
voicevox_core.workspace = true
wasm-bindgen = "0.2.87"
